name: Notifications
on:
  push:
  pull_request:
    types: ['opened', 'closed']
jobs:
  push_notification:
    name: Push Notification
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Push Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ‚òëÔ∏è <code>${{ github.event.head_commit.message }}</code>
            <b>${{ github.actor }}</b> <em>pushed</em> to <b>${{ github.ref }}</b> 
            üìÇ ${{ github.repository }}
            üîó <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">view changes</a>
  pull_request_notification_opened:
    name: Pull Request Notification (Opened)
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Pull Open Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <code>${{ github.event.pull_request.title }}</code>
            <b>PR opened</b>
            <b>${{ github.actor }}</b> opened PR 
            <b>${{ github.repository }}</b>
            ${{ github.event.pull_request.html_url }}
      - uses: actions/checkout@master
  pull_request_notification_closed:
    name: Pull Request Notification (Closed)
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Pull Close Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <code>${{ github.event.pull_request.title }}</code>
            <b>PR closed</b>
            <b>${{ github.actor }}</b> closed PR 
            <b>${{ github.repository }}</b>
            ${{ github.event.pull_request.html_url }}
